name: Basic CI Testing
on: [push]
jobs:
  Run-CI-on-Ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Modules
        run: yarn
      - name: Run tests
        run: yarn Test-environment-with-Jest
  Run-CI-on-Windows:
    runs-on: windows-2019
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Modules
        run: yarn
      - name: Run tests
        run: yarn Test-environment-with-Jest
  Run-CI-on-MacOS10:
    runs-on: macos-10.15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Modules
        run: yarn
      - name: Run tests
        run: yarn Test-environment-with-Jest
